version: "3.7"

services:
  app:
    image: url_shorter
    build: .
    container_name: url_shorter
    restart: always
    ports:
      - 8000:443
    volumes:
      - type: bind
        source: ./config/config.json
        target: /app/config/config.json