openapi: 3.0.1
info:
  title: Url-shortener
  version: 1.0.0
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "API key to authorize requests."
  schemas:
    link:
      type: object
      properties:
        id:
          type: string
        user_id:
          type: string
        short_url:
          type: string
        full_url:
          type: string
        usage_count:
          type: integer
        created_at:
          type: string
    user:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        login:
          type: string
        password:
          type: string
        created_at:
          type: string
        deleted_at:
          type: string
    userRegist:
      type: object
      required:
        - name
        - login
        - password
      properties:
        name:
          type: string
        login:
          type: string
        password:
          type: string
    userLogin:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    userAccount:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        login:
          type: string
    linkCreate:
      type: object
      properties:
        short_url:
          type: string
        full_url:
          type: string
tags:
  - name: public
    description: Публичные методы
  - name: auth
    description: Операции с сессией пользователя
  - name: account
    description: Операции с аккаунтом
  - name: links
    description: Операции с ссылками
paths:
  /use-url:
    get:
      tags:
        - public
      summary: Поиск полной ссылки для перехода
      parameters:
        - name: "short_url"
          in: query
          description: Короткий url по которому будет найден полный url
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  fullUrl:
                    type: string
        204:
          description: Не найдено
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /regist:
    post:
      tags:
        - auth
      summary: Регистрация
      description: Регистрация пользователей
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userRegist"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  userId:
                    type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /login:
    post:
      tags:
        - auth
      summary: Авторизация
      description: Данный метод возвращает токен
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userLogin"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  token:
                    type: string
        400:
          description: Неправильный логин или пароль
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /logout:
    post:
      tags:
        - auth
      summary: Выход из текущей сессии
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /links:
    post:
      summary: Добавление новой ссылки
      tags:
        - links
      security:
        - jwt: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/linkCreate"
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/link"
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    get:
      summary: Вывод ссылок пользователя
      tags:
        - links
      security:
        - jwt: []
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/link'
  /links/{linkId}:
    get:
      summary: Вывод ссылки пользователя
      tags:
        - links
      security:
        - jwt: []
      parameters:
        - name: "linkId"
          in: path
          required: true
          description: ID ссылки
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/link'
    put:
      summary: Обновление ссылки
      tags:
        - links
      security:
        - jwt: []
      parameters:
        - name: "linkId"
          in: path
          description: ID ссылки
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              properties:
                short_url:
                  type: string
                  description: Update short_url of the element
                full_url:
                  type: string
                  description: Update full_url of the element
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/link"
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Удаление ссылки
      security:
        - jwt: []
      tags:
        - links
      parameters:
        - name: "linkId"
          in: path
          description: ID ссылки
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /account:
    get:
      summary: Вывод данных пользователя
      security:
        - jwt: []
      tags:
        - account
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userAccount"
    put:
      summary: Обновление пользователя
      tags:
        - account
      security:
        - jwt: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                  description: Update name of the user
                password:
                  type: string
                  description: Update password of the user
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    delete:
      summary: Удаление аккаунта
      tags:
        - account
      security:
        - jwt: []
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
