// Package oapirouter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package oapirouter

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	Api_keyScopes = "api_key.Scopes"
)

// Link defines model for link.
type Link struct {
	CreatedAt  *string `json:"created_at,omitempty"`
	FullUrl    *string `json:"full_url,omitempty"`
	Id         *string `json:"id,omitempty"`
	ShortUrl   *string `json:"short_url,omitempty"`
	UsageCount *int    `json:"usage_count,omitempty"`
	UserId     *string `json:"user_id,omitempty"`
}

// User defines model for user.
type User struct {
	CreatedAt *string `json:"created_at,omitempty"`
	DeletedAt *string `json:"deleted_at,omitempty"`
	Id        *string `json:"id,omitempty"`
	Login     *string `json:"login,omitempty"`
	Name      *string `json:"name,omitempty"`
	Password  *string `json:"password,omitempty"`
}

// PostLinksParams defines parameters for PostLinks.
type PostLinksParams struct {
	// Body Поля пользователя
	Body Link `form:"body" json:"body"`
}

// PutLinksLinkIdJSONBody defines parameters for PutLinksLinkId.
type PutLinksLinkIdJSONBody struct {
	// FullUrl Update full_url of the element
	FullUrl *string `json:"full_url,omitempty"`

	// ShortUrl Update short_url of the element
	ShortUrl *string `json:"short_url,omitempty"`
}

// PostUseUrlParams defines parameters for PostUseUrl.
type PostUseUrlParams struct {
	// ShortUrl Короткий url по которому будет найден полный url
	ShortUrl string `form:"short_url" json:"short_url"`
}

// PostUserLoginParams defines parameters for PostUserLogin.
type PostUserLoginParams struct {
	// Login Логин авторизации
	Login string `form:"login" json:"login"`

	// Password Пароль авторизации
	Password string `form:"password" json:"password"`
}

// PutUsersUserIdJSONBody defines parameters for PutUsersUserId.
type PutUsersUserIdJSONBody struct {
	// Name Update name of the user
	Name *string `json:"name,omitempty"`
}

// PutLinksLinkIdJSONRequestBody defines body for PutLinksLinkId for application/json ContentType.
type PutLinksLinkIdJSONRequestBody PutLinksLinkIdJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = User

// PutUsersUserIdJSONRequestBody defines body for PutUsersUserId for application/json ContentType.
type PutUsersUserIdJSONRequestBody PutUsersUserIdJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вывод ссылок пользователя
	// (GET /links)
	GetLinks(c *gin.Context)
	// Добавление новой ссылки
	// (POST /links)
	PostLinks(c *gin.Context, params PostLinksParams)
	// Удаление ссылки
	// (DELETE /links/{linkId})
	DeleteLinksLinkId(c *gin.Context, linkId string)
	// Вывод ссылки пользователя
	// (GET /links/{linkId})
	GetLinksLinkId(c *gin.Context, linkId string)
	// Обновление ссылки
	// (PUT /links/{linkId})
	PutLinksLinkId(c *gin.Context, linkId string)
	// Поиск полной ссылки для перехода
	// (POST /use-url)
	PostUseUrl(c *gin.Context, params PostUseUrlParams)
	// Авторизация
	// (POST /user/login)
	PostUserLogin(c *gin.Context, params PostUserLoginParams)
	// Выход из текущей сессии
	// (POST /user/logout)
	PostUserLogout(c *gin.Context)
	// Создание пользователя
	// (POST /users)
	PostUsers(c *gin.Context)
	// Удаление пользователя
	// (DELETE /users/{userId})
	DeleteUsersUserId(c *gin.Context, userId string)
	// Вывод данных пользователя
	// (GET /users/{userId})
	GetUsersUserId(c *gin.Context, userId string)
	// Обновление пользователя
	// (PUT /users/{userId})
	PutUsersUserId(c *gin.Context, userId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetLinks operation middleware
func (siw *ServerInterfaceWrapper) GetLinks(c *gin.Context) {

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLinks(c)
}

// PostLinks operation middleware
func (siw *ServerInterfaceWrapper) PostLinks(c *gin.Context) {

	var err error

	c.Set(Api_keyScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params PostLinksParams

	// ------------- Required query parameter "body" -------------

	if paramValue := c.Query("body"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument body is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "body", c.Request.URL.Query(), &params.Body)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter body: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostLinks(c, params)
}

// DeleteLinksLinkId operation middleware
func (siw *ServerInterfaceWrapper) DeleteLinksLinkId(c *gin.Context) {

	var err error

	// ------------- Path parameter "linkId" -------------
	var linkId string

	err = runtime.BindStyledParameter("simple", false, "linkId", c.Param("linkId"), &linkId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter linkId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteLinksLinkId(c, linkId)
}

// GetLinksLinkId operation middleware
func (siw *ServerInterfaceWrapper) GetLinksLinkId(c *gin.Context) {

	var err error

	// ------------- Path parameter "linkId" -------------
	var linkId string

	err = runtime.BindStyledParameter("simple", false, "linkId", c.Param("linkId"), &linkId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter linkId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetLinksLinkId(c, linkId)
}

// PutLinksLinkId operation middleware
func (siw *ServerInterfaceWrapper) PutLinksLinkId(c *gin.Context) {

	var err error

	// ------------- Path parameter "linkId" -------------
	var linkId string

	err = runtime.BindStyledParameter("simple", false, "linkId", c.Param("linkId"), &linkId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter linkId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutLinksLinkId(c, linkId)
}

// PostUseUrl operation middleware
func (siw *ServerInterfaceWrapper) PostUseUrl(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostUseUrlParams

	// ------------- Required query parameter "short_url" -------------

	if paramValue := c.Query("short_url"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument short_url is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "short_url", c.Request.URL.Query(), &params.ShortUrl)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter short_url: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUseUrl(c, params)
}

// PostUserLogin operation middleware
func (siw *ServerInterfaceWrapper) PostUserLogin(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostUserLoginParams

	// ------------- Required query parameter "login" -------------

	if paramValue := c.Query("login"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument login is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "login", c.Request.URL.Query(), &params.Login)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter login: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "password" -------------

	if paramValue := c.Query("password"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument password is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "password", c.Request.URL.Query(), &params.Password)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter password: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserLogin(c, params)
}

// PostUserLogout operation middleware
func (siw *ServerInterfaceWrapper) PostUserLogout(c *gin.Context) {

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUserLogout(c)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsers(c)
}

// DeleteUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteUsersUserId(c, userId)
}

// GetUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersUserId(c, userId)
}

// PutUsersUserId operation middleware
func (siw *ServerInterfaceWrapper) PutUsersUserId(c *gin.Context) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameter("simple", false, "userId", c.Param("userId"), &userId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(Api_keyScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutUsersUserId(c, userId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/links", wrapper.GetLinks)
	router.POST(options.BaseURL+"/links", wrapper.PostLinks)
	router.DELETE(options.BaseURL+"/links/:linkId", wrapper.DeleteLinksLinkId)
	router.GET(options.BaseURL+"/links/:linkId", wrapper.GetLinksLinkId)
	router.PUT(options.BaseURL+"/links/:linkId", wrapper.PutLinksLinkId)
	router.POST(options.BaseURL+"/use-url", wrapper.PostUseUrl)
	router.POST(options.BaseURL+"/user/login", wrapper.PostUserLogin)
	router.POST(options.BaseURL+"/user/logout", wrapper.PostUserLogout)
	router.POST(options.BaseURL+"/users", wrapper.PostUsers)
	router.DELETE(options.BaseURL+"/users/:userId", wrapper.DeleteUsersUserId)
	router.GET(options.BaseURL+"/users/:userId", wrapper.GetUsersUserId)
	router.PUT(options.BaseURL+"/users/:userId", wrapper.PutUsersUserId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYTW/bRhP+K8S+75GxlDQnHYsAhVEfChQ+GYZBi2uJCUUyu8sWgiHAH2iLwAFSFDm1",
	"aIqif4BWLViWLOUvzP6jYoYUqQ9KpPwV2xdL3NXOzjzPPDPDQ1b3W4HvcU9JVjtkst7kLYs+uo73Bv8H",
	"wg+4UA6np3XBLcXtPUvhN9UOOKsxqYTjNVjHZAeh6+6Fws1ddOzcx7LpC7X0R6G0Gnyv7ofetEXHU7zB",
	"RbyBi73cozvm5Im//5rX1WT32l7Z3OUrlpf45foNx8td8awWz10ILCl/9EU5ZzB0vB4KR7W/R9hiV6zA",
	"2XvD2/gRrbMmt2wu2MRoup4eZwXOt7zNOnie4x34ZNtRLq5tC/cZwcM9OuMHLqTj47HPN6obVbyyH3DP",
	"ChxWY19tVDeeM3RCNekqFaQQfWpwihyG3FKO723arMa+4WqLNphMcBn4now9eFGtEia+p3gMuhUErlOn",
	"X1ZeS9/LmEpuKt6iH/5f8ANWY/+rZJyuJISmq7AshpYQVuKzzWVdOIGK/ZJhvc6lPAhdI73tTKhZbWcq",
	"yDu7nV2TybDVskSb1Rj8ps+gC2O4MPSxPtZnMIQxDAz4DGMY6vdwCWPoQqRPoAdD/QFhsBqS1XbifNtF",
	"EvgyJ1rf+TINV2AJq8UVF5JuM+sB/EWmPqyyScx4G3LRzoix79ttguJt6Ahus5oSITen4lwcXozFraAs",
	"YaIkYiZ7Gdue3bxv2QZ6yKVaB9WPMIZziKALQ+jBCPrQM2BEYR3DVQb1APqLiHbMJBMqh/hv0+7E90JN",
	"WcT5FT0npLdodxHem6/m7RO6mIUZuO7kqOXwzuvNEizXCn5p4GfluMUlqn45FVwgxA0x/gcuIJrCdzWo",
	"5mpNe5TQfYE0vJVwDqC/nnCGeboZ3h8iBQgQBb9GWb15Kkw3VLNX3Q5sS3FjssHwDwzV5AZ3eQvtmAWN",
	"Vu5h6Y7C0+jv8an9UxKcT3Ce1JCyooOVJJT8WQLh8kZhW/Jt4RZ2Cr/DWB/BWJ+gObgyEHhMOAMG9JRW",
	"4VqfGnCuT+ECevoE614EV/gFRkl6wkifxT9f0ltkzHuaMmayF9WXi1kDf8Z9QBoPGMcEyEDGZqyvj9MW",
	"kBC/mtO4i0m/1tNH0NM/oQxCNIV/EO67Tj1jgKikw8WEBHM3+wgRjBJc4BqBI20lib2Erj6CSL+DiBCl",
	"tQHen5n5ZBJbZK6IT3/AGP6FPvIigm5CoD5cQqR/hn4mp3PscJPDyzPDzGl6IyLrUL9fz3g6cj0kMxfE",
	"9L5krtAQUhg+Ix2gC32qtAlphhmYfRjGpTiN8TzNf12M+EyNtkLVnKOvH1frlSKGvMN9XybcazUvcdZi",
	"rC4NalIG+lS/gx4lO/Qw4RMWLomJLI6GZDdvK1aJIb0UuYOCPltU8dRN+4Y19XZTXYbM36R3F6SGNLUV",
	"95MUjSlcKoexJyXGNgJpO/a7uNMsGtBnu85wcuzDjnD3MluVR2H5nPU0Yn2n+Xl/M1eSISPUsbXQWTZz",
	"PUZ07mIem7y6zR2fcHEyOVGE1hmbHj4r8waQNfSxkz5a7Mb0KZxj06B/oXaiN9WD6rOp5ivua3P6uU9J",
	"N5w0b4Y+ni6jWFVX3HTyqhsLbLmzIYIBDCDSpzCia17P0q30FdO2PoJrqvZT7wxYZ7fzXwAAAP//mXX0",
	"OXEZAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
